=== phaupt/sipproxy/testcases/TestCaseSchema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="TestCase">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Variables" type="Variables" minOccurs="0"/>
				<xs:element name="Request" type="Request" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="cycles" type="xs:integer" use="optional"/>
			<xs:attribute name="initialRequestMessageID" type="xs:integer" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Variables">
		<xs:sequence>
			<xs:element name="Var" type="Var" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Var">
		<xs:sequence>
			<xs:element ref="Module"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="Request">
		<xs:sequence>
			<xs:element name="MessageModifier" type="MessageModifier" minOccurs="0"/>
			<xs:element name="Variables" type="Variables" minOccurs="0"/>
			<xs:element name="Timeout" type="Timeout" minOccurs="0"/>
			<xs:element name="Content" type="xs:string"/>
			<xs:element name="Response" type="Response" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="requestID" type="xs:integer" use="required"/>
	</xs:complexType>
	<xs:complexType name="MessageModifier">
		<xs:sequence>
			<xs:element ref="MessageModifierAbstract" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="MessageModifierAbstract" type="MessageModifierAbstractType" abstract="true"/>
	<xs:complexType name="MessageModifierAbstractType"/>
	<xs:element name="LinePermutator" type="LinePermutatorType" substitutionGroup="MessageModifierAbstract"/>
	<xs:complexType name="LinePermutatorType">
		<xs:complexContent>
			<xs:extension base="MessageModifierAbstractType">
				<xs:attribute name="startLine" type="xs:integer" use="required"/>
				<xs:attribute name="endLine" type="xs:integer" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="ContentLength" type="ContentLengthType" substitutionGroup="MessageModifierAbstract"/>
	<xs:complexType name="ContentLengthType">
		<xs:complexContent>
			<xs:extension base="MessageModifierAbstractType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="Timeout">
		<xs:attribute name="timeInMilliseconds" type="xs:integer" use="required"/>
		<xs:attribute name="message" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="Response">
		<xs:sequence>
			<xs:element name="Regex" type="xs:string"/>
			<xs:element name="ResponseVariables" type="ResponseVariables" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="category" type="categoryValues" use="required"/>
		<xs:attribute name="followingRequestID" type="xs:integer" use="optional"/>
		<xs:attribute name="waitingTimeInMilliseconds" type="xs:integer" use="optional"/>
	</xs:complexType>
	<xs:simpleType name="categoryValues">
		<xs:restriction base="xs:string">
			<xs:enumeration value="okay"/>
			<xs:enumeration value="warning"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="ResponseVariables">
		<xs:sequence>
			<xs:element name="ResponseVar" type="ResponseVar" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ResponseVar">
		<xs:sequence>
			<xs:element ref="ResponseCatcher"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:element name="ResponseCatcher" type="ResponseCatcherType"/>
	<xs:complexType name="ResponseCatcherType">
		<xs:sequence>
			<xs:element name="Regex" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="catchGroupIndex" type="xs:integer" use="required"/>
	</xs:complexType>
	<xs:element name="Module" type="ModuleType" abstract="true"/>
	<xs:complexType name="ModuleType"/>
	<xs:element name="ClearText" type="ClearTextType" substitutionGroup="Module"/>
	<xs:complexType name="ClearTextType" mixed="true">
		<xs:complexContent mixed="true">
			<xs:extension base="ModuleType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="ConfigValue" type="ConfigValueType" substitutionGroup="Module"/>
	<xs:complexType name="ConfigValueType">
		<xs:complexContent>
			<xs:extension base="ModuleType">
				<xs:attribute name="paramName" type="configValues" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:simpleType name="configValues">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ProxySocketIP"/>
			<xs:enumeration value="ProxySocketPort"/>
			<xs:enumeration value="PbxIP"/>
			<xs:enumeration value="PbxPort"/>
			<xs:enumeration value="ClientIP"/>
			<xs:enumeration value="ClientPort"/>
			<xs:enumeration value="TestCaseSocketIP"/>
			<xs:enumeration value="TestCaseSocketPort"/>
			<xs:enumeration value="TargetIP"/>
			<xs:enumeration value="TargetPort"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="NumberRangeFuzzer" type="NumberRangeFuzzerType" substitutionGroup="Module"/>
	<xs:complexType name="NumberRangeFuzzerType">
		<xs:complexContent>
			<xs:extension base="ModuleType">
				<xs:attribute name="minimum" type="xs:integer" use="required"/>
				<xs:attribute name="maximum" type="xs:integer" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="StringMutationFuzzer" type="StringMutationFuzzerType" substitutionGroup="Module"/>
	<xs:complexType name="StringMutationFuzzerType">
		<xs:complexContent>
			<xs:extension base="ModuleType">
				<xs:sequence>
					<xs:element ref="CharacterSet" minOccurs="0"/>
				</xs:sequence>
				<xs:attribute name="length" type="xs:integer" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="StringExpansionFuzzer" type="StringExpansionFuzzerType" substitutionGroup="Module"/>
	<xs:complexType name="StringExpansionFuzzerType">
		<xs:complexContent>
			<xs:extension base="ModuleType">
				<xs:choice>
					<xs:element ref="CharacterSet" minOccurs="0"/>
					<xs:element name="ExpansionString" type="xs:string" minOccurs="0"/>
				</xs:choice>
				<xs:attribute name="increment" type="xs:integer" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="NumberCounter" type="NumberCounterType" substitutionGroup="Module"/>
	<xs:complexType name="NumberCounterType" mixed="true">
		<xs:complexContent mixed="true">
			<xs:extension base="ModuleType">
				<xs:attribute name="startValue" type="xs:integer" use="required"/>
				<xs:attribute name="counterIncrement" type="xs:integer" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="CharacterSet" type="xs:string"/>
	<xs:element name="ValueListFuzzer" type="ValueListFuzzerType" substitutionGroup="Module"/>
	<xs:complexType name="ValueListFuzzerType" mixed="true">
		<xs:complexContent mixed="true">
			<xs:extension base="ModuleType">
				<xs:attribute name="repeatValueList" type="xs:boolean" use="required"/>
				<xs:attribute name="filePath" type="xs:string" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="HexValueListFuzzer" type="HexValueListFuzzerType" substitutionGroup="ValueListFuzzer"/>
	<xs:complexType name="HexValueListFuzzerType">
		<xs:complexContent>
			<xs:extension base="ValueListFuzzerType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="Digest" type="DigestType" substitutionGroup="Module"/>
	<xs:complexType name="DigestType">
		<xs:complexContent>
			<xs:extension base="ModuleType">
				<xs:attribute name="username" type="xs:string" use="required"/>
				<xs:attribute name="secret" type="xs:string" use="required"/>
				<xs:attribute name="realm" type="xs:string" use="required"/>
				<xs:attribute name="nonce" type="xs:string" use="required"/>
				<xs:attribute name="uri" type="xs:string" use="required"/>
				<xs:attribute name="method" type="xs:string" use="required"/>
				<xs:attribute name="qop" type="xs:string" use="optional"/>
				<xs:attribute name="noncecount" type="xs:string" use="optional"/>
				<xs:attribute name="cnonce" type="xs:string" use="optional"/>
				<xs:attribute name="body" type="xs:string" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== phaupt/sipproxy/testcases/AuthenticatedRegisterAndInvite.xml
<TestCase cycles="1" initialRequestMessageID="1" name="Authenticated REGISTER and INVITE" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TestCaseSchema.xsd">
	
	<Variables>
		<Var name="attackerNr">
			<ClearText><![CDATA[1111]]></ClearText>
		</Var>
		<Var name="targetNr">
			<ClearText><![CDATA[2222]]></ClearText>
		</Var>
		<Var name="attackerIP">
			<ConfigValue paramName="TestCaseSocketIP"/>
		</Var>
		<Var name="attackerPort">
			<ConfigValue paramName="TestCaseSocketPort"/>
		</Var>
		<Var name="targetIP">
			<ConfigValue paramName="TargetIP"/>
		</Var>
		<Var name="call_ID_REGISTER">
			<StringMutationFuzzer length="10"/>
		</Var>
		<Var name="call_ID_INVITE">
			<StringMutationFuzzer length="10"/>
		</Var>
		<Var name="sdp_ID">
			<NumberRangeFuzzer minimum="100000000" maximum="999999999"/>
		</Var>
		<Var name="secret">
			<ClearText>123456</ClearText>
		</Var>
	</Variables>
	
	<Request requestID="1">
		<Timeout timeInMilliseconds="2000" message="no answer"/>
		<Content><![CDATA[REGISTER sip:/'targetIP'/ SIP/2.0
Via: SIP/2.0/UDP /'attackerIP'/:/'attackerPort'/
Max-Forwards: 20
To: <sip:/'attackerNr'/@/'targetIP'/>
From: <sip:/'attackerNr'/@/'attackerIP'/>;tag=RegisterAndInviteAttempt
Call-ID: /'call_ID_REGISTER'/@/'targetIP'/
CSeq: 1 REGISTER
Contact: <sip:/'attackerNr'/@/'attackerIP'/:/'attackerPort'/>
Content-Length: 0

]]></Content>
		<Response category="warning">
			<!-- REGISTER was accepted by the Proxy -->
			<Regex><![CDATA[(SIP/2.0 200)((.*)(\r\n))+(Call-ID: /'call_ID_REGISTER'/@/'targetIP'/)]]></Regex>
		</Response>
		<Response category="okay" followingRequestID="21" waitingTimeInMilliseconds="500">
			<!-- Proxy Authentication Required -->
			<Regex><![CDATA[(SIP/2.0 407)((.*)(\r\n))+(Call-ID: /'call_ID_REGISTER'/@/'targetIP'/)]]></Regex>
			<ResponseVariables>
				<ResponseVar name="nonceRegister">
					<ResponseCatcher catchGroupIndex="2">
						<Regex><![CDATA[(nonce=")(.*?)(")]]></Regex>
					</ResponseCatcher>
				</ResponseVar>
				<ResponseVar name="realmRegister">
					<ResponseCatcher catchGroupIndex="2">
						<Regex><![CDATA[(realm=")(.*?)(")]]></Regex>
					</ResponseCatcher>
				</ResponseVar>
				<ResponseVar name="opaque">
					<ResponseCatcher catchGroupIndex="2">
						<Regex><![CDATA[(opaque=")(.*?)(")]]></Regex>
					</ResponseCatcher>
				</ResponseVar>
			</ResponseVariables>
		</Response>
		<Response category="okay" followingRequestID="22" waitingTimeInMilliseconds="500">
			<!-- Proxy Authentication Required -->
			<Regex><![CDATA[(SIP/2.0 401)((.*)(\r\n))+(Call-ID: /'call_ID_REGISTER'/@/'targetIP'/)]]></Regex>
			<ResponseVariables>
				<ResponseVar name="nonceRegister">
					<ResponseCatcher catchGroupIndex="2">
						<Regex><![CDATA[(nonce=")(.*?)(")]]></Regex>
					</ResponseCatcher>
				</ResponseVar>
				<ResponseVar name="realmRegister">
					<ResponseCatcher catchGroupIndex="2">
						<Regex><![CDATA[(realm=")(.*?)(")]]></Regex>
					</ResponseCatcher>
				</ResponseVar>
			</ResponseVariables>
		</Response>

	</Request>
	
	<Request requestID="21">
		<Variables>
			<Var name="digestRegister">
				<Digest realm="/'realmRegister'/" uri="sip:/'attackerIP'/" username="/'attackerNr'/" secret="/'secret'/" nonce="/'nonceRegister'/" method="REGISTER"/>
			</Var>
		</Variables>
		<Timeout timeInMilliseconds="2000" message="no answer"/>
		<Content><![CDATA[REGISTER sip:/'targetIP'/ SIP/2.0
Via: SIP/2.0/UDP /'attackerIP'/:/'attackerPort'/
Max-Forwards: 20
To: <sip:/'attackerNr'/@/'targetIP'/>
From: <sip:/'attackerNr'/@/'attackerIP'/>;tag=RegisterAndInviteAttempt
Call-ID: /'call_ID_REGISTER'/@/'targetIP'/
CSeq: 2 REGISTER
Contact: <sip:/'attackerNr'/@/'attackerIP'/:/'attackerPort'/>
Proxy-Authorization: Digest username="/'attackerNr'/",realm="/'realmRegister'/",nonce="/'nonceRegister'/",uri="sip:/'attackerIP'/",response="/'digestRegister'/",opaque="/'opaque'/"
Content-Length: 0

]]></Content>
		<Response category="warning">
			<!-- REGISTER Authentication was not accepted -->
			<Regex><![CDATA[(SIP/2.0 4)((.*)(\r\n))+(Call-ID: /'call_ID_REGISTER'/@/'targetIP'/)]]></Regex>
		</Response>
		<Response category="okay" followingRequestID="3" waitingTimeInMilliseconds="500">
			<!-- REGISTER was accepted by the Proxy -->
			<Regex><![CDATA[(SIP/2.0 200)((.*)(\r\n))+(Call-ID: /'call_ID_REGISTER'/@/'targetIP'/)]]></Regex>
		</Response>
	</Request>

	<Request requestID="22">
		<Variables>
			<Var name="digestRegister">
				<Digest realm="/'realmRegister'/" uri="sip:/'attackerIP'/" username="/'attackerNr'/" secret="/'secret'/" nonce="/'nonceRegister'/" method="REGISTER"/>
			</Var>
		</Variables>
		<Timeout timeInMilliseconds="2000" message="no answer"/>
		<Content><![CDATA[REGISTER sip:/'targetIP'/ SIP/2.0
Via: SIP/2.0/UDP /'attackerIP'/:/'attackerPort'/
Max-Forwards: 20
To: <sip:/'attackerNr'/@/'targetIP'/>
From: <sip:/'attackerNr'/@/'attackerIP'/>;tag=RegisterAndInviteAttempt
Call-ID: /'call_ID_REGISTER'/@/'targetIP'/
CSeq: 2 REGISTER
Contact: <sip:/'attackerNr'/@/'attackerIP'/:/'attackerPort'/>
Authorization: Digest username="/'attackerNr'/",realm="/'realmRegister'/",nonce="/'nonceRegister'/",uri="sip:/'attackerIP'/",response="/'digestRegister'/"
Content-Length: 0

]]></Content>
		<Response category="warning">
			<!-- REGISTER Authentication was not accepted -->
			<Regex><![CDATA[(SIP/2.0 4)((.*)(\r\n))+(Call-ID: /'call_ID_REGISTER'/@/'targetIP'/)]]></Regex>
		</Response>
		<Response category="okay" followingRequestID="3" waitingTimeInMilliseconds="500">
			<!-- REGISTER was accepted by the Proxy -->
			<Regex><![CDATA[(SIP/2.0 200)((.*)(\r\n))+(Call-ID: /'call_ID_REGISTER'/@/'targetIP'/)]]></Regex>
		</Response>
	</Request>
	
	<Request requestID="3">
		<MessageModifier>
			<ContentLength/>
		</MessageModifier>
		<Timeout timeInMilliseconds="2000" message="no answer"/>
		<Content><![CDATA[INVITE sip:/'targetNr'/@/'targetIP'/ SIP/2.0
Via: SIP/2.0/UDP /'attackerIP'/:/'attackerPort'/
To: <sip:/'targetNr'/@/'targetIP'/>
From: "attacker" <sip:/'attackerNr'/@/'targetIP'/>;tag=RegisterAndInviteAttempt
Call-ID: /'call_ID_INVITE'/@/'targetIP'/
CSeq: 3 INVITE
Max-Forwards: 20
Contact: <sip:/'attackerNr'/@/'attackerIP'/:/'attackerPort'/>
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, INFO, REFER, NOTIFY
Supported: replaces
Content-Type: application/sdp
Content-Length: ?

v=0
o=- /'sdp_ID'/ /'sdp_ID'/ IN IP4 /'attackerIP'/
s=Attacker
c=IN IP4 /'attackerIP'/
t=0 0
m=audio 8000 RTP/AVP 0 8 96 3 13 101
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:96 G726-32/8000
a=rtpmap:3 GSM/8000
a=rtpmap:13 CN/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=sendrecv
a=direction:active
]]></Content>
		<Response category="okay" followingRequestID="4" waitingTimeInMilliseconds="500">
			<!-- Proxy Authentication Required -->
			<Regex><![CDATA[(SIP/2.0 407)((.*)(\r\n))+(Call-ID: /'call_ID_INVITE'/@/'targetIP'/)]]></Regex>
			<ResponseVariables>
				<ResponseVar name="nonceInvite">
					<ResponseCatcher catchGroupIndex="2">
						<Regex><![CDATA[(nonce=")(.*?)(")]]></Regex>
					</ResponseCatcher>
				</ResponseVar>
				<ResponseVar name="realmInvite">
					<ResponseCatcher catchGroupIndex="2">
						<Regex><![CDATA[(realm=")(.*?)(")]]></Regex>
					</ResponseCatcher>
				</ResponseVar>
			</ResponseVariables>
		</Response>
	</Request>	
	
	<Request requestID="4">
		<MessageModifier>
			<ContentLength/>
		</MessageModifier>
		<Variables>
			<Var name="digestInvite">
				<Digest realm="/'realmInvite'/" uri="sip:/'targetNr'/@/'attackerIP'/" username="/'attackerNr'/" secret="/'secret'/" nonce="/'nonceInvite'/" method="INVITE"/>
			</Var>
		</Variables>	
		<Timeout timeInMilliseconds="2000" message="no answer"/>
		<Content><![CDATA[INVITE sip:/'targetNr'/@/'targetIP'/ SIP/2.0
Via: SIP/2.0/UDP /'attackerIP'/:/'attackerPort'/
To: <sip:/'targetNr'/@/'targetIP'/>
From: "attacker" <sip:/'attackerNr'/@/'targetIP'/>;tag=RegisterAndInviteAttempt
Call-ID: /'call_ID_INVITE'/@/'targetIP'/
CSeq: 4 INVITE
Max-Forwards: 20
Contact: <sip:/'attackerNr'/@/'attackerIP'/:/'attackerPort'/>
Proxy-Authorization: Digest username="/'attackerNr'/",realm="/'realmInvite'/",nonce="/'nonceInvite'/",uri="sip:/'targetNr'/@/'attackerIP'/",response="/'digestInvite'/"
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, INFO, REFER, NOTIFY
Supported: replaces
Content-Type: application/sdp
Content-Length: ?

v=0
o=- /'sdp_ID'/ /'sdp_ID'/ IN IP4 192.168.0.19
s=Attacker
c=IN IP4 192.168.0.3
t=0 0
m=audio 8000 RTP/AVP 0 8 96 3 13 101
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:96 G726-32/8000
a=rtpmap:3 GSM/8000
a=rtpmap:13 CN/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=sendrecv
a=direction:active
]]></Content>
		<Response category="warning">
			<!-- INVITE Authentication was not accepted -->
			<Regex><![CDATA[(SIP/2.0 4)((.*)(\r\n))+(Call-ID: /'call_ID_INVITE'/@/'targetIP'/)]]></Regex>
		</Response>
		<Response category="okay">
			<!-- INVITE was accepted by the Proxy -->
			<Regex><![CDATA[(SIP/2.0 100)((.*)(\r\n))+(Call-ID: /'call_ID_INVITE'/@/'targetIP'/)]]></Regex>
		</Response>
	</Request>
	
</TestCase>

=== phaupt/sipproxy/testcases/ThirdPartyRegisterFlooding.xml
<TestCase cycles="200" initialRequestMessageID="1" name="Third-Party REGISTER flooding" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TestCaseSchema.xsd">
	
	<Variables>
		<Var name="targetNr">
			<ClearText><![CDATA[1111]]></ClearText>
		</Var>
		<Var name="attackerIP">
			<ConfigValue paramName="TestCaseSocketIP"/>
		</Var>
		<Var name="attackerPort">
			<ConfigValue paramName="TestCaseSocketPort"/>
		</Var>
		<Var name="targetIP">
			<ConfigValue paramName="TargetIP"/>
		</Var>
		<Var name="call_ID_REGISTER">
			<StringMutationFuzzer length="10"/>
		</Var>
		<Var name="call_ID_INVITE">
			<StringMutationFuzzer length="10"/>
		</Var>
		<Var name="ip">
			<NumberCounter startValue="0" counterIncrement="1"/>
		</Var>
		<Var name="sdp_ID">
			<NumberRangeFuzzer minimum="100000000" maximum="999999999"/>
		</Var>
		<Var name="secret">
			<ClearText>123456</ClearText>
		</Var>
	</Variables>
	
	<Request requestID="1">
		<Timeout timeInMilliseconds="2000" message="no answer"/>
		<Content><![CDATA[REGISTER sip:192.168.0./'ip'/ SIP/2.0
Via: SIP/2.0/UDP /'attackerIP'/:/'attackerPort'/
Max-Forwards: 20
To: <sip:/'targetNr'/@/'targetIP'/>
From: <sip:/'targetNr'/@/'targetIP'/>
Call-ID: /'call_ID_REGISTER'/@/'targetIP'/
CSeq: 1 REGISTER
Contact: <sip:/'targetNr'/@192.168.0./'ip'/:/'attackerPort'/>
Content-Length: 0

]]></Content>
		<Response category="warning">
			<!-- REGISTER was accepted by the Proxy -->
			<Regex><![CDATA[(SIP/2.0 2)((.*)(\r\n))+(Call-ID: /'call_ID_REGISTER'/@/'targetIP'/)]]></Regex>
		</Response>
		<Response category="okay" followingRequestID="2">
			<!-- Proxy Authentication Required -->
			<Regex><![CDATA[(SIP/2.0 4)((.*)(\r\n))+(Call-ID: /'call_ID_REGISTER'/@/'targetIP'/)]]></Regex>
			<ResponseVariables>
				<ResponseVar name="nonceRegister">
					<ResponseCatcher catchGroupIndex="2">
						<Regex><![CDATA[(nonce=")(.*?)(")]]></Regex>
					</ResponseCatcher>
				</ResponseVar>
				<ResponseVar name="realmRegister">
					<ResponseCatcher catchGroupIndex="2">
						<Regex><![CDATA[(realm=")(.*?)(")]]></Regex>
					</ResponseCatcher>
				</ResponseVar>
			</ResponseVariables>
		</Response>
	</Request>
	
	<Request requestID="2">
		<Variables>
			<Var name="digestRegister">
				<Digest realm="/'realmRegister'/" uri="sip:/'attackerIP'/" username="/'targetNr'/" secret="/'secret'/" nonce="/'nonceRegister'/" method="REGISTER"/>
			</Var>
		</Variables>
		<Timeout timeInMilliseconds="2000" message="no answer"/>
		<Content><![CDATA[REGISTER sip:192.168.0./'ip'/ SIP/2.0
Via: SIP/2.0/UDP /'attackerIP'/:/'attackerPort'/
Max-Forwards: 20
To: <sip:/'targetNr'/@/'targetIP'/>
From: <sip:/'targetNr'/@/'targetIP'/>
Call-ID: /'call_ID_REGISTER'/@/'targetIP'/
CSeq: 2 REGISTER
Contact: <sip:/'targetNr'/@192.168.0./'ip'/:/'attackerPort'/>
Authorization: Digest username="/'targetNr'/",realm="/'realmRegister'/",nonce="/'nonceRegister'/",uri="sip:/'attackerIP'/",response="/'digestRegister'/"
Content-Length: 0

]]></Content>
		<Response category="warning">
			<!-- REGISTER Authentication was not accepted -->
			<Regex><![CDATA[(SIP/2.0 4)((.*)(\r\n))+(Call-ID: /'call_ID_REGISTER'/@/'targetIP'/)]]></Regex>
		</Response>
		<Response category="okay">
			<!-- Third Party REGISTER was accepted by the Proxy -->
			<Regex><![CDATA[(SIP/2.0 2)((.*)(\r\n))+(Call-ID: /'call_ID_REGISTER'/@/'targetIP'/)]]></Regex>
		</Response>
	</Request>
	
</TestCase>

=== phaupt/sipproxy/testcases/UnauthenticatedRegisterAttempt.xml
<TestCase cycles="10" initialRequestMessageID="1" name="Unauthenticated REGISTER Attempt" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TestCaseSchema.xsd">

	<Variables>
		<Var name="attackerNr">
			<ClearText><![CDATA[1111]]></ClearText>
		</Var>
		<Var name="attackerIP">
			<ConfigValue paramName="TestCaseSocketIP"/>
		</Var>
		<Var name="attackerPort">
			<ConfigValue paramName="TestCaseSocketPort"/>
		</Var>
		<Var name="targetIP">
			<ConfigValue paramName="TargetIP"/>
		</Var>
		<Var name="call_ID">
			<StringMutationFuzzer length="10">
				<CharacterSet><![CDATA[a-z,0-9]]></CharacterSet>
			</StringMutationFuzzer>
		</Var>
	</Variables>
	
	<Request requestID="1">
		<Timeout timeInMilliseconds="2000" message="no answer"/>
		<Content><![CDATA[REGISTER sip:/'targetIP'/ SIP/2.0
Via: SIP/2.0/UDP /'attackerIP'/:/'attackerPort'/
Max-Forwards: 20
To: <sip:/'attackerNr'/@/'targetIP'/>
From: <sip:/'attackerNr'/@/'attackerIP'/>;tag=RegisterAndInviteAttempt
Call-ID: /'call_ID'/@/'targetIP'/
CSeq: 1 REGISTER
Contact: <sip:/'attackerNr'/@/'attackerIP'/:/'attackerPort'/>
Content-Length: 0

]]></Content>
		<Response category="warning" waitingTimeInMilliseconds="500">
			<!-- REGISTER was accepted by the Proxy -->
			<Regex><![CDATA[(SIP/2.0 200)((.*)(\r\n))+(Call-ID: /'call_ID'/@/'targetIP'/)]]></Regex>
		</Response>
		<Response category="okay" waitingTimeInMilliseconds="500">
			<!-- Proxy Authentication Required -->
			<Regex><![CDATA[(SIP/2.0 4)((.*)(\r\n))+(Call-ID: /'call_ID'/@/'targetIP'/)]]></Regex>
		</Response>
	</Request>
	
</TestCase>

=== phaupt/sipproxy/testcases/UnauthorizedInviteFuzzingAttack.xml
<TestCase initialRequestMessageID="1" name="Unauthorized INVITE fuzzing attack" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TestCaseSchema.xsd">

	<Variables>
		<Var name="attackerNr">
			<ClearText><![CDATA[1111]]></ClearText>
		</Var>
		<Var name="targetNr">
			<ClearText><![CDATA[2222]]></ClearText>
		</Var>
		<Var name="attackerIP">
			<ConfigValue paramName="TestCaseSocketIP"/>
		</Var>
		<Var name="attackerPort">
			<ConfigValue paramName="TestCaseSocketPort"/>
		</Var>
		<Var name="targetIP">
			<ConfigValue paramName="TargetIP"/>
		</Var>
		<Var name="call_ID">
			<StringMutationFuzzer length="20">
				<CharacterSet><![CDATA[A-Z,0-9]]></CharacterSet>
			</StringMutationFuzzer>
		</Var>
		<Var name="sdp_ID">
			<NumberRangeFuzzer minimum="100000000" maximum="999999999"/>
		</Var>
		<Var name="expFuzzer">
			<StringExpansionFuzzer increment="1000">
				<CharacterSet><![CDATA[\\]]></CharacterSet>
			</StringExpansionFuzzer>
		</Var>
	</Variables>
	
	<Request requestID="1">
		<MessageModifier>
			<ContentLength/>
		</MessageModifier>
		<Timeout timeInMilliseconds="3000" message="no answer"/>
		<Content><![CDATA[INVITE sip:/'targetNr'/@/'targetIP'/ SIP/2.0
Via: SIP/2.0/UDP /'attackerIP'/:/'attackerPort'/
To: <sip:/'targetNr'/@/'targetIP'/>
From: "attacker" <sip:/'attackerNr'/@/'expFuzzer'/>;tag=InviteFuzzingAttack
Call-ID: /'call_ID'/@/'targetIP'/
CSeq: 1 INVITE
Max-Forwards: 20
Contact: <sip:/'attackerNr'/@/'attackerIP'/:/'attackerPort'/>
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, INFO, REFER, NOTIFY
Supported: replaces
Content-Type: application/sdp
Content-Length: ?

v=0
o=- /'sdp_ID'/ /'sdp_ID'/ IN IP4 /'attackerIP'/
s=Attacker
c=IN IP4 /'attackerIP'/
t=0 0
m=audio 8000 RTP/AVP 0 8 96 3 13 101
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:96 G726-32/8000
a=rtpmap:3 GSM/8000
a=rtpmap:13 CN/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=sendrecv
a=direction:active
]]></Content>
		<Response category="warning">
			<!-- Unauthorized INVITE was successful -->
			<Regex><![CDATA[(SIP/2.0 1)((.*)(\r\n))+(Call-ID: /'call_ID'/@/'targetIP'/)]]></Regex>
		</Response>
		<Response category="okay">
			<!-- Proxy Authentication Required -->
			<Regex><![CDATA[(SIP/2.0 407)((.*)(\r\n))+(Call-ID: /'call_ID'/@/'targetIP'/)]]></Regex>
		</Response>
	</Request>
	
</TestCase>
