=== phaupt/sipproxy/testcases/TestCaseSchema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="TestCase">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Variables" type="Variables" minOccurs="0"/>
				<xs:element name="Request" type="Request" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="cycles" type="xs:integer" use="optional"/>
			<xs:attribute name="initialRequestMessageID" type="xs:integer" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Variables">
		<xs:sequence>
			<xs:element name="Var" type="Var" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Var">
		<xs:sequence>
			<xs:element ref="Module"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="Request">
		<xs:sequence>
			<xs:element name="MessageModifier" type="MessageModifier" minOccurs="0"/>
			<xs:element name="Variables" type="Variables" minOccurs="0"/>
			<xs:element name="Timeout" type="Timeout" minOccurs="0"/>
			<xs:element name="Content" type="xs:string"/>
			<xs:element name="Response" type="Response" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="requestID" type="xs:integer" use="required"/>
	</xs:complexType>
	<xs:complexType name="MessageModifier">
		<xs:sequence>
			<xs:element ref="MessageModifierAbstract" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="MessageModifierAbstract" type="MessageModifierAbstractType" abstract="true"/>
	<xs:complexType name="MessageModifierAbstractType"/>
	<xs:element name="LinePermutator" type="LinePermutatorType" substitutionGroup="MessageModifierAbstract"/>
	<xs:complexType name="LinePermutatorType">
		<xs:complexContent>
			<xs:extension base="MessageModifierAbstractType">
				<xs:attribute name="startLine" type="xs:integer" use="required"/>
				<xs:attribute name="endLine" type="xs:integer" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="ContentLength" type="ContentLengthType" substitutionGroup="MessageModifierAbstract"/>
	<xs:complexType name="ContentLengthType">
		<xs:complexContent>
			<xs:extension base="MessageModifierAbstractType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="Timeout">
		<xs:attribute name="timeInMilliseconds" type="xs:integer" use="required"/>
		<xs:attribute name="message" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="Response">
		<xs:sequence>
			<xs:element name="Regex" type="xs:string"/>
			<xs:element name="ResponseVariables" type="ResponseVariables" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="category" type="categoryValues" use="required"/>
		<xs:attribute name="followingRequestID" type="xs:integer" use="optional"/>
		<xs:attribute name="waitingTimeInMilliseconds" type="xs:integer" use="optional"/>
	</xs:complexType>
	<xs:simpleType name="categoryValues">
		<xs:restriction base="xs:string">
			<xs:enumeration value="okay"/>
			<xs:enumeration value="warning"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="ResponseVariables">
		<xs:sequence>
			<xs:element name="ResponseVar" type="ResponseVar" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ResponseVar">
		<xs:sequence>
			<xs:element ref="ResponseCatcher"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:element name="ResponseCatcher" type="ResponseCatcherType"/>
	<xs:complexType name="ResponseCatcherType">
		<xs:sequence>
			<xs:element name="Regex" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="catchGroupIndex" type="xs:integer" use="required"/>
	</xs:complexType>
	<xs:element name="Module" type="ModuleType" abstract="true"/>
	<xs:complexType name="ModuleType"/>
	<xs:element name="ClearText" type="ClearTextType" substitutionGroup="Module"/>
	<xs:complexType name="ClearTextType" mixed="true">
		<xs:complexContent mixed="true">
			<xs:extension base="ModuleType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="ConfigValue" type="ConfigValueType" substitutionGroup="Module"/>
	<xs:complexType name="ConfigValueType">
		<xs:complexContent>
			<xs:extension base="ModuleType">
				<xs:attribute name="paramName" type="configValues" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:simpleType name="configValues">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ProxySocketIP"/>
			<xs:enumeration value="ProxySocketPort"/>
			<xs:enumeration value="PbxIP"/>
			<xs:enumeration value="PbxPort"/>
			<xs:enumeration value="ClientIP"/>
			<xs:enumeration value="ClientPort"/>
			<xs:enumeration value="TestCaseSocketIP"/>
			<xs:enumeration value="TestCaseSocketPort"/>
			<xs:enumeration value="TargetIP"/>
			<xs:enumeration value="TargetPort"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="NumberRangeFuzzer" type="NumberRangeFuzzerType" substitutionGroup="Module"/>
	<xs:complexType name="NumberRangeFuzzerType">
		<xs:complexContent>
			<xs:extension base="ModuleType">
				<xs:attribute name="minimum" type="xs:integer" use="required"/>
				<xs:attribute name="maximum" type="xs:integer" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="StringMutationFuzzer" type="StringMutationFuzzerType" substitutionGroup="Module"/>
	<xs:complexType name="StringMutationFuzzerType">
		<xs:complexContent>
			<xs:extension base="ModuleType">
				<xs:sequence>
					<xs:element ref="CharacterSet" minOccurs="0"/>
				</xs:sequence>
				<xs:attribute name="length" type="xs:integer" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="StringExpansionFuzzer" type="StringExpansionFuzzerType" substitutionGroup="Module"/>
	<xs:complexType name="StringExpansionFuzzerType">
		<xs:complexContent>
			<xs:extension base="ModuleType">
				<xs:choice>
					<xs:element ref="CharacterSet" minOccurs="0"/>
					<xs:element name="ExpansionString" type="xs:string" minOccurs="0"/>
				</xs:choice>
				<xs:attribute name="increment" type="xs:integer" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="NumberCounter" type="NumberCounterType" substitutionGroup="Module"/>
	<xs:complexType name="NumberCounterType" mixed="true">
		<xs:complexContent mixed="true">
			<xs:extension base="ModuleType">
				<xs:attribute name="startValue" type="xs:integer" use="required"/>
				<xs:attribute name="counterIncrement" type="xs:integer" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="CharacterSet" type="xs:string"/>
	<xs:element name="ValueListFuzzer" type="ValueListFuzzerType" substitutionGroup="Module"/>
	<xs:complexType name="ValueListFuzzerType" mixed="true">
		<xs:complexContent mixed="true">
			<xs:extension base="ModuleType">
				<xs:attribute name="repeatValueList" type="xs:boolean" use="required"/>
				<xs:attribute name="filePath" type="xs:string" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="HexValueListFuzzer" type="HexValueListFuzzerType" substitutionGroup="ValueListFuzzer"/>
	<xs:complexType name="HexValueListFuzzerType">
		<xs:complexContent>
			<xs:extension base="ValueListFuzzerType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="Digest" type="DigestType" substitutionGroup="Module"/>
	<xs:complexType name="DigestType">
		<xs:complexContent>
			<xs:extension base="ModuleType">
				<xs:attribute name="username" type="xs:string" use="required"/>
				<xs:attribute name="secret" type="xs:string" use="required"/>
				<xs:attribute name="realm" type="xs:string" use="required"/>
				<xs:attribute name="nonce" type="xs:string" use="required"/>
				<xs:attribute name="uri" type="xs:string" use="required"/>
				<xs:attribute name="method" type="xs:string" use="required"/>
				<xs:attribute name="qop" type="xs:string" use="optional"/>
				<xs:attribute name="noncecount" type="xs:string" use="optional"/>
				<xs:attribute name="cnonce" type="xs:string" use="optional"/>
				<xs:attribute name="body" type="xs:string" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== phaupt/sipproxy/testcases/SampleTestCase.xml
<TestCase cycles="3" initialRequestMessageID="1" name="Sample Test Case" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TestCaseSchema.xsd">
	<Variables>
		<!-- Following different variables can be defined -->
		<Var name="ClearText">
			<ClearText>clear text variable content</ClearText>
		</Var>
		<Var name="ConfigValueTargetIP">
			<ConfigValue paramName="TargetIP"/>
		</Var>		
		<Var name="NumberCounter">
			<NumberCounter startValue="10" counterIncrement="2"/>
		</Var>
		<Var name="NumberRangeFuzzer">
			<NumberRangeFuzzer minimum="-10" maximum="100000"/>
		</Var>
		<Var name="StringMutationFuzzerRandom">
			<StringMutationFuzzer length="15"/>
		</Var>
		<Var name="StringMutationFuzzerCharset">
			<StringMutationFuzzer length="15">
				<CharacterSet>a-z,0-9,X,Y,Z</CharacterSet>
			</StringMutationFuzzer>
		</Var>		
		<Var name="StringExpansionFuzzerRandom">
			<StringExpansionFuzzer increment="1"/>
		</Var>
		<Var name="StringExpansionFuzzerCharSet">
			<StringExpansionFuzzer increment="2">
				<CharacterSet>
				<![CDATA[a-z,0-9,\,,\\,#]]>
				</CharacterSet>
			</StringExpansionFuzzer>
		</Var>
		<Var name="ValueListFuzzerFile">
			<ValueListFuzzer repeatValueList="true" filePath="TestCases/sampleValueList.txt"/>
		</Var>
		<Var name="ValueListFuzzerList">
			<ValueListFuzzer repeatValueList="false">
				<![CDATA[ValueListFuzzerList 1
ValueListFuzzerList 2
ValueListFuzzerList 3
ValueListFuzzerList 4]]>
			</ValueListFuzzer>
		</Var>		
		<Var name="HexValueListFuzzerFile">
			<HexValueListFuzzer repeatValueList="false" filePath="TestCases/sampleHexValueList.txt"/>
		</Var>
				
		<Var name="HexValueListFuzzerList">
			<HexValueListFuzzer repeatValueList="true">
				<![CDATA[0x480x650x780x560x610x6C0x750x650x4C0x690x730x740x460x750x7A0x7A0x650x720x4C0x690x730x740x200x31
0x480x650x780x560x610x6C0x750x650x4C0x690x730x740x460x750x7A0x7A0x650x720x4C0x690x730x740x200x32
0x480x650x780x560x610x6C0x750x650x4C0x690x730x740x460x750x7A0x7A0x650x720x4C0x690x730x740x200x33
0x480x650x780x560x610x6C0x750x650x4C0x690x730x740x460x750x7A0x7A0x650x720x4C0x690x730x740x200x34]]>
			</HexValueListFuzzer>
		</Var>
	</Variables>
	<Request requestID="1">
		<MessageModifier>
			<LinePermutator startLine="3" endLine="5"/>
		</MessageModifier>		
		<Variables>
			<Var name="attackerNr">
				<ClearText><![CDATA[1111]]></ClearText>
			</Var>
			<Var name="targetNr">
				<ClearText><![CDATA[2222]]></ClearText>
			</Var>
			<Var name="attackerIP">
				<ConfigValue paramName="TestCaseSocketIP"/>
			</Var>
			<Var name="attackerPort">
				<ConfigValue paramName="TestCaseSocketPort"/>
			</Var>
			<Var name="targetIP">
				<ConfigValue paramName="TargetIP"/>
			</Var>
			<Var name="call_ID_REGISTER">
				<StringMutationFuzzer length="10"/>
			</Var>
			<Var name="call_ID_INVITE">
				<StringMutationFuzzer length="10"/>
			</Var>
			<Var name="sdp_ID">
				<NumberRangeFuzzer minimum="100000000" maximum="999999999"/>
			</Var>			
		</Variables>
		<Timeout timeInMilliseconds="2000" message="no answer"/>		
		<Content><![CDATA[REGISTER sip:/'targetIP'/ SIP/2.0
Via: SIP/2.0/UDP /'attackerIP'/:/'attackerPort'/
Max-Forwards: 20
To: <sip:/'attackerNr'/@/'targetIP'/>
From: <sip:/'attackerNr'/@/'attackerIP'/>;tag=RegisterAndInviteAttempt
Call-ID: /'call_ID_REGISTER'/@/'targetIP'/
CSeq: 1 REGISTER
Contact: <sip:/'attackerNr'/@/'attackerIP'/:/'attackerPort'/>
Content-Length: 0
]]></Content>
		<Response category="warning">
			<!-- REGISTER was accepted by the Proxy -->
			<Regex><![CDATA[(SIP/2.0 200)((.*)(\r\n))+(Call-ID: /'call_ID_REGISTER'/@/'targetIP'/)]]></Regex>
		</Response>
		<Response category="okay" followingRequestID="2" waitingTimeInMilliseconds="500">
			<!-- Proxy Authentication Required -->
			<Regex><![CDATA[(SIP/2.0 401)((.*)(\r\n))+(Call-ID: /'call_ID_REGISTER'/@/'targetIP'/)]]></Regex>
			<ResponseVariables>
				<ResponseVar name="ResponseCatcherNonce">
					<ResponseCatcher catchGroupIndex="2">
						<Regex><![CDATA[(nonce=")(.*?)(")]]></Regex>
					</ResponseCatcher>
				</ResponseVar>
				<ResponseVar name="ResponseCatcherRealm">
					<ResponseCatcher catchGroupIndex="2">
						<Regex><![CDATA[(realm=")(.*?)(")]]></Regex>
					</ResponseCatcher>
				</ResponseVar>
			</ResponseVariables>
		</Response>
	</Request>
	<Request requestID="2">
		<MessageModifier>
			<LinePermutator startLine="3" endLine="10"/>			
			<ContentLength/>
		</MessageModifier>			
		<Variables>
			<Var name="secret">
				<ClearText>123456</ClearText>
			</Var>
			<Var name="Digest">
				<Digest realm="/'ResponseCatcherRealm'/" uri="sip:/'attackerIP'/" username="/'attackerNr'/" secret="/'secret'/" nonce="/'nonceRegister'/" method="REGISTER"/>
			</Var>
		</Variables>
		<Timeout timeInMilliseconds="2000" message="test cycle end"/>
				
		<Content>
<![CDATA[Content-Length: ?

ClearText: /'ClearText'/
ConfigValueTargetIP: /'ConfigValueTargetIP'/			
NumberCounter: /'NumberCounter'/
NumberRangeFuzzer: /'NumberRangeFuzzer'/			
StringMutationFuzzerRandom: /'StringMutationFuzzerRandom'/
StringMutationFuzzerCharset: /'StringMutationFuzzerCharset'/
StringExpansionFuzzerRandom: /'StringExpansionFuzzerRandom'/
StringExpansionFuzzerCharSet: /'StringExpansionFuzzerCharSet'/
Content-Length: ?

ValueListFuzzerFile: /'ValueListFuzzerFile'/
ValueListFuzzerList: /'ValueListFuzzerList'/
HexValueListFuzzerFile: /'HexValueListFuzzerFile'/
HexValueListFuzzerList: /'HexValueListFuzzerList'/			
ResponseCatcherNonce: /'ResponseCatcherNonce'/
ResponseCatcherRealm: /'ResponseCatcherRealm'/
Digest:/'Digest'/]]>
		</Content>
		<Response category="warning">
			<!-- REGISTER Authentication was not accepted -->
			<Regex><![CDATA[(SIP/2.0 4)((.*)(\r\n))+(Call-ID: /'call_ID_REGISTER'/@/'targetIP'/)]]></Regex>
		</Response>
		<Response category="okay" followingRequestID="3" waitingTimeInMilliseconds="500">
			<!-- REGISTER was accepted by the Proxy -->
			<Regex><![CDATA[(SIP/2.0 200)((.*)(\r\n))+(Call-ID: /'call_ID_REGISTER'/@/'targetIP'/)]]></Regex>
		</Response>
	</Request>
</TestCase>

=== phaupt/sipproxy/testcases/UnsuspectedNotify.xml
<TestCase cycles="1" initialRequestMessageID="1" name="Unsuspected NOTIFY" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TestCaseSchema.xsd">
	
	<Variables>
		<Var name="pbxIP">
			<ConfigValue paramName="PbxIP"/>
		</Var>
		<Var name="pbxPort">
			<ConfigValue paramName="PbxPort"/>
		</Var>
		<Var name="myIP">
			<ConfigValue paramName="TestCaseSocketIP"/>
		</Var>
		<Var name="myPort">
			<ConfigValue paramName="TestCaseSocketPort"/>
		</Var>
		<Var name="targetIP">
			<ConfigValue paramName="TargetIP"/>
		</Var>
		<Var name="targetPort">
			<ConfigValue paramName="TargetPort"/>
		</Var>
		<Var name="targetNr">
			<ClearText>2222</ClearText>
		</Var>
		<Var name="counter1">
			<NumberCounter startValue="100"></NumberCounter>
		</Var>
	</Variables>
	
	<Request requestID="1">
		<MessageModifier>
			<ContentLength/>
		</MessageModifier>
		<Content><![CDATA[NOTIFY sip:/'targetNr'/@/'targetIP'/ SIP/2.0
Via: SIP/2.0/UDP /'myIP'/:/'myPort'/
From: "attacker" <sip:attacker@/'pbxIP'/>
To: <sip:/'targetNr'/@/'targetIP'/>
Contact: <sip:1111@/'myIP'/:/'myPort'/>
Call-ID: 00000000000000@/'pbxIP'/
CSeq: /'counter1'/ NOTIFY
Event: message-summary
Content-Type: application/simple-message-summary
Content-Length: 39

Messages-Waiting: yes
]]>		
		</Content>
		<Response category="warning">
			<Regex><![CDATA[SIP/2.0 200 OK]]></Regex>
		</Response>
		<Response category="okay">
			<Regex><![CDATA[SIP/2.0 481]]></Regex>
		</Response>
	</Request>
	
</TestCase>

=== phaupt/sipproxy/src/junit/testexec/TestCase1.xml
<TestCase name="TestCase1" cycles="1" initialRequestMessageID="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\..\persistence\TestCaseSchema.xsd">
	<Variables>
		<Var name="AsteriskIPAddress">
			<ConfigValue paramName="PbxIP"/>
		</Var>
		<Var name="TargetNr">
			<ClearText><![CDATA[121212]]></ClearText>
		</Var>
		<Var name="numberRangeFuzzer">
			<NumberRangeFuzzer minimum="0" maximum="1000"/>
		</Var>
		<Var name="stringMutationFuzzer">
			<StringMutationFuzzer length="10"/>
		</Var>
		<Var name="stringExpansionFuzzer">
			<StringExpansionFuzzer increment="5">
				<ExpansionString><![CDATA[abcd]]></ExpansionString>
			</StringExpansionFuzzer>
		</Var>
		<Var name="hexValueListFuzzer">
			<HexValueListFuzzer filePath="hexValues.dat"/>
		</Var>
		<Var name="valueListFuzzer">
			<ValueListFuzzer>
<![CDATA[value1
value2
value3]]>			
			</ValueListFuzzer>
		</Var>
	</Variables>
	<Request requestID="1">
		<Content><![CDATA[REGISTER sip:192.168.0.18 SIP/2.0
Via: SIP/2.0/UDP 192.168.0.15:5060;rport;branch=z9hG4bK297DEC382B8D4F99ACE64DAF8A83F16F
From: testclient <sip:343434@192.168.0.18>;tag=3779692192
To: testclient <sip:343434@192.168.0.18>
Contact: "testclient" <sip:343434@192.168.0.15:5060>
Call-ID: 85E8F6630642436AA7FE49BEEAD3CE7F@192.168.0.18
CSeq: 27427 REGISTER
Expires: 1800
Max-Forwards: 70
User-Agent: X-Lite release 1105x
Content-Length: 0

]]></Content>
		<Response category="okay" followingRequestID="2" waitingTimeInMilliseconds="10000">
			<Regex><![CDATA[SIP/2.0 (401|407)(.)*]]></Regex>
			<ResponseVariables>
				<ResponseVar name="nonce">
					<ResponseCatcher replacement="2">
						<Regex><![CDATA[(nonce=\")(.*)(\")]]></Regex>
					</ResponseCatcher>
				</ResponseVar>
			</ResponseVariables>
		</Response>
		<Response category="warning">
			<Regex><![CDATA[SIP/2.0 200 Ok]]></Regex>
		</Response>
	</Request>
	<Request requestID="2">
		<Variables>
		<Var name="digest">
			<Digest username="alice" secret="123456" realm="asterisk" nonce="/'nonce'/" uri="biloxi.com" method="REGISTER"/>
		</Var>
		</Variables>
		<Timeout timeInMilliseconds="2000" message="uups"/>
		<Content><![CDATA[REGISTER sip:*98@192.168.0.18 SIP/2.0
Via: SIP/2.0/UDP 192.168.0.20:5060;rport;branch=z9hG4bK34CB63B2EA8F4726BCEB993CDA5EB4D3
From: "tester" <sip:1111@192.168.0.18>;tag=474754342
To: "tester" <sip:1111@192.168.0.18>
Contact: <sip:1111@192.168.0.20:5060>
Call-ID: /'TargetNr'/A-FF54-4108-959C-42/'fStringExp'/@192.168.0.20/'hexValue'/
CSeq: 14960 REGISTER
Max-Forwards: 70
Content-Type: application/sdp
User-Agent: X-Lite release 1105x
Content-Length: 0
]]></Content>
		<Response category="warning">
			<Regex><![CDATA[SIP/2.0 200 Ok]]></Regex>
		</Response>
	</Request>
</TestCase>

=== phaupt/sipproxy/src/junit/persistence/SampleTestCaseSpecification.xml
<TestCase name="SampleTestCaseSpecification" cycles="10" initialRequestMessageID="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../persistence/TestCaseSchema.xsd">
	<Variables>
		<Var name="AsteriskIPAddress">
			<ConfigValue paramName="PbxIP"/>
		</Var>
		<Var name="TargetNr">
			<ClearText><![CDATA[121212]]></ClearText>
		</Var>
		<Var name="numberRangeFuzzer">
			<NumberRangeFuzzer minimum="0" maximum="1000"/>
		</Var>
		<Var name="stringMutationFuzzer">
			<StringMutationFuzzer length="10">
				<CharacterSet>
					<![CDATA[a-c,!,#,\-]]>
				</CharacterSet>
			</StringMutationFuzzer>
		</Var>
		<Var name="stringExpansionFuzzer1">
			<StringExpansionFuzzer increment="5">
				<ExpansionString><![CDATA[abcd]]></ExpansionString>
			</StringExpansionFuzzer>
		</Var>
		<Var name="stringExpansionFuzzer2">
			<StringExpansionFuzzer increment="6">
				<CharacterSet>
					<![CDATA[a-c,!,#,\-]]>
				</CharacterSet>
			</StringExpansionFuzzer>
		</Var>		
		<Var name="hexValueListFuzzer">
			<HexValueListFuzzer filePath="hexValueList.txt" repeatValueList="false"/>
		</Var>
		<Var name="valueListFuzzer">
			<ValueListFuzzer filePath="valueList.txt" repeatValueList="false"/>
		</Var>
		<Var name="digest">
			<Digest username="alice" secret="123456" realm="asterisk" nonce="ABABAB" uri="biloxi.com" method="REGISTER" qop="AUTH-INT" noncecount="CDCDCD" cnonce="DEDEDE" body="EFEFEF"/>
		</Var>
	</Variables>
	<Request requestID="1">
		<Content><![CDATA[REGISTER sip:192.168.0.18 SIP/2.0
Via: SIP/2.0/UDP 192.168.0.15:5060;rport;branch=z9hG4bK297DEC382B8D4F99ACE64DAF8A83F16F
From: testclient <sip:343434@192.168.0.18>;tag=3779692192
To: testclient <sip:343434@192.168.0.18>
Contact: "testclient" <sip:343434@192.168.0.15:5060>
Call-ID: 85E8F6630642436AA7FE49BEEAD3CE7F@192.168.0.18
CSeq: 27427 REGISTER
Expires: 1800
Max-Forwards: 70
User-Agent: X-Lite release 1105x
Content-Length: 0

]]></Content>
		<Response category="okay" followingRequestID="2" waitingTimeInMilliseconds="10000">
			<Regex><![CDATA[SIP/2.0 (401|407)(.)*]]></Regex>
			<ResponseVariables>
				<ResponseVar name="nonce">
					<ResponseCatcher catchGroupIndex="2">
						<Regex><![CDATA[(nonce=")(.*)(")]]></Regex>
					</ResponseCatcher>
				</ResponseVar>
			</ResponseVariables>
		</Response>
		<Response category="warning">
			<Regex><![CDATA[SIP/2.0 200 Ok]]></Regex>
		</Response>
	</Request>
	<Request requestID="2">
		<Timeout timeInMilliseconds="1000" message="uups"/>
		<Content><![CDATA[SIP/2.0 401 Unauthorized
Via: SIP/2.0/UDP 192.168.0.18:5060;rport;branch=z9hG4bK297DEC382B8D4F99ACE64DAF8A83F16F;received=192.168.0.18
From: testclient <sip:343434@192.168.0.10>;tag=3779692192
To: testclient <sip:343434@192.168.0.10>;tag=as5eaff1ef
Call-ID: 85E8F6630642436AA7FE49BEEAD3CE7F@192.168.0.10
CSeq: 27427 REGISTER
User-Agent: Asterisk PBX
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY
Contact: <sip:343434@192.168.0.10>
WWW-Authenticate: Digest realm="asterisk", nonce="30419c6c"
Content-Length: 0

]]></Content>
		<Response category="warning">
			<Regex><![CDATA[SIP/2.0 401]]></Regex>
		</Response>
	</Request>
</TestCase>

=== phaupt/sipproxy/src/testexec/TestCaseVariables.xml
<TestCase cycles="10" initialRequestMessageID="1" name="TestCase Example 1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="src\persistence\TestCaseSchema.xsd">
	<Variables>
		<Var name="targetNr">
			<ClearText><![CDATA[1111]]></ClearText>
		</Var>
		<Var name="pbxIP">
			<ConfigValue paramName="PbxIP"/>
		</Var>
		<Var name="proxyIP">
			<ConfigValue paramName="ProxyIP"/>
		</Var>
		<Var name="proxyPort">
			<ConfigValue paramName="ProxyPort"/>
		</Var>
		<Var name="fStringExp">
			<StringExpansionFuzzer increment="1"/>
		</Var>
		<Var name="hexValue">
			<HexValueListFuzzer filePath="hexValues.dat"/>
		</Var>
	</Variables>
	<Request id="1">
		<Content><![CDATA[INVITE sip:*98@/'pbxIP'/ SIP/2.0
Via: SIP/2.0/UDP /'proxyIP'/:/'proxyPort'/;rport
From: "tester" <sip:/'targetNr'/@/'pbxIP'/>;tag=474754342
To: "*98"<sip:*98@/'pbxIP'/>
Contact: <sip:/'targetNr'/@/'proxyIP'/:/'proxyPort'/>
Call-ID: A-FF54-4108-959C-42/'fStringExp'/@/'proxyIP'//'hexValue'/
CSeq: 14959 INVITE
Max-Forwards: 70
Content-Type: application/sdp
User-Agent: X-Lite release 1105x
Content-Length: 309

v=0
o=121212 265542245 265542271 IN IP4 192.168.0.20
s=X-Lite
c=IN IP4 192.168.0.20
t=0 0
m=audio 8000 RTP/AVP 0 8 3 98 97 101
a=rtpmap:0 pcmu/8000
a=rtpmap:8 pcma/8000
a=rtpmap:3 gsm/8000
a=rtpmap:98 iLBC/8000
a=rtpmap:97 speex/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendrecv

]]></Content>
		<Response category="okay" followingRequestID="2" waitingTimeInMilliseconds="10000">
			<Regex><![CDATA[SIP/2.0 (401|407)(.)*]]></Regex>
		</Response>
		<Response category="warning">
			<Regex><![CDATA[SIP/2.0 200 Ok]]></Regex>
		</Response>
	</Request>
	<Request id="2">
		<Timeout timeInMilliseconds="2000" message="dont know"/>
		<Content><![CDATA[REGISTER sip:*98@/'pbxIP'/ SIP/2.0
Via: SIP/2.0/UDP /'proxyIP'/:/'proxyPort'/;rport;branch=z9hG4bK34CB63B2EA8F4726BCEB993CDA5EB4D3
From: "tester" <sip:/'targetNr'/@/'pbxIP'/>;tag=474754342
To: "tester" <sip:/'targetNr'/@'pbxIP'/>
Contact: <sip:/'targetNr'/@/'proxyIP'/:/'proxyPort'/>
Call-ID: A-FF54-4108-959C-42/'fStringExp'/@/'proxyIP'//'hexValue'/
CSeq: 14960 REGISTER
Max-Forwards: 70
Content-Type: application/sdp
User-Agent: SIP Proxy
Content-Length: 0
]]></Content>
		<Response category="okay">
			<Regex><![CDATA[SIP/2.0 (x401|x407)(.)*]]></Regex>
		</Response>
		<Response category="warning">
			<Regex><![CDATA[SIP/2.0 200 Ok]]></Regex>
		</Response>
	</Request>
</TestCase>

=== phaupt/sipproxy/testcases/AuthenticatedRegisterFlooding.xml
<TestCase initialRequestMessageID="1" name="Authenticated REGISTER flooding" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TestCaseSchema.xsd">
	
	<Variables>
		<Var name="attackerNr">
			<ClearText><![CDATA[1111]]></ClearText>
		</Var>
		<Var name="attackerIP">
			<ConfigValue paramName="TestCaseSocketIP"/>
		</Var>
		<Var name="attackerPort">
			<ConfigValue paramName="TestCaseSocketPort"/>
		</Var>
		<Var name="targetIP">
			<ConfigValue paramName="TargetIP"/>
		</Var>
		<Var name="call_ID">
			<StringMutationFuzzer length="10"/>
		</Var>
		<Var name="sdp_ID">
			<NumberRangeFuzzer minimum="100000000" maximum="999999999"/>
		</Var>
		<Var name="secret">
			<ClearText>123456</ClearText>
		</Var>
	</Variables>
	
	<Request requestID="1">
		<Timeout timeInMilliseconds="2000" message="Unauthenticated REGISTER timeout"/>
		<Content><![CDATA[REGISTER sip:/'targetIP'/ SIP/2.0
Via: SIP/2.0/UDP /'attackerIP'/:/'attackerPort'/
Max-Forwards: 20
To: <sip:/'attackerNr'/@/'targetIP'/>
From: <sip:/'attackerNr'/@/'attackerIP'/>;tag=RegisterFlooding
Call-ID: /'call_ID'/@/'targetIP'/
CSeq: 1 REGISTER
Contact: <sip:/'attackerNr'/@/'attackerIP'/:/'attackerPort'/>
Content-Length: 0

]]></Content>
		<Response category="warning">
			<!-- REGISTER was accepted by the Proxy -->
			<Regex><![CDATA[(SIP/2.0 200)((.*)(\r\n))+(Call-ID: /'call_ID'/@/'targetIP'/)]]></Regex>
		</Response>
		<Response category="okay" followingRequestID="2">
			<!-- Proxy Authentication Required -->
			<Regex><![CDATA[(SIP/2.0 407)((.*)(\r\n))+(Call-ID: /'call_ID'/@/'targetIP'/)]]></Regex>
			<ResponseVariables>
				<ResponseVar name="nonceRegister">
					<ResponseCatcher catchGroupIndex="2">
						<Regex><![CDATA[(nonce=")(.*?)(")]]></Regex>
					</ResponseCatcher>
				</ResponseVar>
				<ResponseVar name="realmRegister">
					<ResponseCatcher catchGroupIndex="2">
						<Regex><![CDATA[(realm=")(.*?)(")]]></Regex>
					</ResponseCatcher>
				</ResponseVar>
				<ResponseVar name="opaque">
					<ResponseCatcher catchGroupIndex="2">
						<Regex><![CDATA[(opaque=")(.*?)(")]]></Regex>
					</ResponseCatcher>
				</ResponseVar>
			</ResponseVariables>
		</Response>
	</Request>
	
	<Request requestID="2">
		<Variables>
			<Var name="digestRegister">
				<Digest realm="/'realmRegister'/" uri="sip:/'attackerIP'/" username="/'attackerNr'/" secret="/'secret'/" nonce="/'nonceRegister'/" method="REGISTER"/>
			</Var>
		</Variables>
		<Timeout timeInMilliseconds="2000" message="Authenticated REGISTER timeout"/>
		<Content><![CDATA[REGISTER sip:/'targetIP'/ SIP/2.0
Via: SIP/2.0/UDP /'attackerIP'/:/'attackerPort'/
Max-Forwards: 20
To: <sip:/'attackerNr'/@/'targetIP'/>
From: <sip:/'attackerNr'/@/'attackerIP'/>;tag=RegisterFlooding
Call-ID: /'call_ID'/@/'targetIP'/
CSeq: 2 REGISTER
Contact: <sip:/'attackerNr'/@/'attackerIP'/:/'attackerPort'/>
Proxy-Authorization: Digest username="/'attackerNr'/",realm="/'realmRegister'/",nonce="/'nonceRegister'/",uri="sip:/'attackerIP'/",response="/'digestRegister'/",opaque="/'opaque'/"
Content-Length: 0

]]></Content>
		<Response category="warning">
			<!-- REGISTER Authentication not accepted -->
			<Regex><![CDATA[(SIP/2.0 4)((.*)(\r\n))+(Call-ID: /'call_ID'/@/'targetIP'/)]]></Regex>
		</Response>
		<Response category="okay">
			<!-- REGISTER accepted by the Proxy -->
			<Regex><![CDATA[(SIP/2.0 200)((.*)(\r\n))+(Call-ID: /'call_ID'/@/'targetIP'/)]]></Regex>
		</Response>
	</Request>
	
</TestCase>
